// <auto-generated />
using Assignment_EasyAPi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment_EasyAPi.Migrations
{
    [DbContext(typeof(EasyDBContext))]
    partial class EasyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment_EasyAPi.Model.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int>("Type1")
                        .HasColumnType("int");

                    b.Property<int>("Type2")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Class = "Physical Attacker",
                            Name = "Forest",
                            Type1 = 1,
                            Type2 = 0
                        },
                        new
                        {
                            ID = 2,
                            Class = "Special Attacker",
                            Name = "City",
                            Type1 = 8,
                            Type2 = 5
                        },
                        new
                        {
                            ID = 3,
                            Class = "Physical Wall",
                            Name = "Mountain",
                            Type1 = 7,
                            Type2 = 2
                        },
                        new
                        {
                            ID = 4,
                            Class = "Special Attacker",
                            Name = "Palace",
                            Type1 = 3,
                            Type2 = 0
                        },
                        new
                        {
                            ID = 5,
                            Class = "Speical Wall",
                            Name = "Heaven",
                            Type1 = 11,
                            Type2 = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
